### PR TITLE
Should search in the names, not in the apps

### PR DESCRIPTION
**Pull request by jimhester**

### CODE REVIEW

**Comment by gaborcsardi** [comment]
Thanks!

**Comment by jimhester** [comment]
Before this PR you get the following behavior.

``` r
x <- cliapp::start_app(.auto_close = FALSE)
cliapp::stop_app(x)
#> Error in match(x, table, nomatch = 0L): 'match' requires vector arguments
```

<sup>Created on 2020-09-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

This is effectively what is happening in https://github.com/r-lib/cliapp/blob/35b184ad35b392da469df54acc701f12470129cb/R/package.R#L65, but the error was being silently ignored because `withr::defer()` previously ignored errors in deferred expressions.

**Comment by jimhester** [comment]
The upcoming release of withr throws an error in these cases, so tests will start to fail in cliapp until this fix is on CRAN.

**Comment by jimhester** [comment]
And callr as well, since it calls cliapp in one of its tests https://github.com/r-lib/callr/blob/29e6277efb9f8fd143eb3c960ceb29ee42bece59/tests/testthat/test-messages.R#L5

**Pull request merged**
